wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.2
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705316567.802673
    t:
      1:
      - 1
      - 9
      - 41
      - 50
      - 55
      - 103
      2:
      - 1
      - 9
      - 41
      - 49
      - 50
      - 55
      - 63
      - 103
      3:
      - 23
      4: 3.10.13
      5: 0.16.2
      8:
      - 3
      - 5
      13: windows-amd64
