_target_: fruity.datamodules.fruits360.Fruits360DataModule
data_dir: data/raw/fruits_360/
batch_size: 128
train_val_test_split: [42_692, 25_000, 22_688]
num_workers: max  # Number of workers to run, or "max" to run all workers
persistent_workers: True
pin_memory: True
num_classes: 131
